version: '3.7'

services:
  devver:
    container_name: devver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_HTTP_TIMEOUT=8000
    tty: true