version: '3.7'
services:
  wikipedia-prod:
    container_name: wikipedia-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'
    environment: 
      - COMPOSE_HTTP_TIMEOUT=8000